version: '3'

services:
  geo-tracking:
    container_name: geo-tracking
    build:
      context: .
    volumes:
      - "./:/app"
    env_file:
      - ".env-docker"
    ports:
      - "80:80"
    entrypoint: ["geo-tracking", "http-server"]

networks:
  default:
    external:
      name: gt


