version: '3'

services:
  redis:
    container_name: redis
    image: redis:7.0.11
    ports:
      - "6379:6379"

  nats:
    container_name: nats
    image: nats:2.9.16
    ports:
      - "4222:4222"
    volumes:
      - "./nats/config:/etc/config"
    command:
        "-c /etc/config/js.conf"


networks:
  default:
    external:
      name: gt
