@startuml
'https://plantuml.com/component-diagram

package "Infrastructure - HTTP" #EB937F {
   [HTTP GET Status] as http_get_status 
}

package "Infrastructure - Event Stream" #EB937F {
   [driver-coordinate.udpated Event] as event_driver_coordinate
}

package "Infrastructure - Distance" #EB937F {
    [Distance Finder] as distance_finder 
}

package "Application" #ADD1B2 {
    http_get_status ---> [Status Service]: Get a driver zombie's status
    event_driver_coordinate --> [Coordinate Service]: 1. Change a driver's coordinate
    [Coordinate Service] --> [Status Service]: 2. Trigger a driver's status computation from coordinates
    distance_finder --> [Status Service]: 3. Compute a driver's distance
}

package "Domain" #B4A7E5 {
    [Coordinate]
    [Status]
    [Distance]

    [Status Service] --> [Status]
    [Status Service] --> [Distance]
    [Status Service] --> [Coordinate]
    
    [Coordinate Service] --> [Coordinate]
}

package "Infrastructure - Persistence" #EB937F {
     database "Redis" {
          folder "cache" {
            [status]
            [coordinate]
          }
}

[Status] -- [status]
[Coordinate] -- [coordinate]

@enduml